### ISSUE TITLE
Unnecessary metadata present in Vaadin 14 generated projects

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/starters#1]
**Describe the bug**
Application created based on Vaadin 14 starters are including a .git directory and other metadata that probably should not be there.

**Comment by anasmi** [comment]
I am not able to reproduce the behavior anymore in the latest starter downloaded from the https://vaadin.com/start/v14

I will close this request due that, but ,please, let me know if I misunderstood the issue or you are creating an application in different way.

Thank you for reporting the issue! :)
