### ISSUE TITLE
Link to alternate page with list of non-Spring starters has disappeared from Settings tab of start.vaadin.com page

### ISSUE THREAD

**Issue by Basil-Dot-Work** [vaadin/starters#101]
**Describe the bug**
Link to page of starters *not* based on Spring used to appear at the bottom of the *Settings* tab on the page:

https://start.vaadin.com/

The missing link led to this page:
https://vaadin.com/hello-world-starters

**To Reproduce**
1. Visit the page: https://start.vaadin.com/
2. Click *Settings* tab
3. Notice that there is no longer any link to the page listing starters for Maven, Gradle, OSGI, plain Servlet, etc.

**Expected behavior**
That page previously offered a handy link.

**Screenshots**
not applicable

**Environment (please complete the following information):**
not applicable

**Additional context**
not applicable

**Comment by jouni** [comment]
You can find that link now in the Vaadin version popup.

<img width="419" alt="Screenshot 2022-12-25 at 16 55 40" src="https://user-images.githubusercontent.com/66382/209472759-2cb05fb5-a9fe-4ffc-b9f5-b29be014d1ca.png">
