### ISSUE TITLE
No spring-boot-starter-data-jpa dependency is included by default

### ISSUE THREAD

**Issue by VGoudkov** [vaadin/starters#104]
**Describe the bug**
https://start.vaadin.com/app generates pom.xml on Java 17 and database PosgreSQL generates pom.xml with missing dependency
<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
**To Reproduce**

1. Create new app and download  [workhours-vaadin23.zip](https://github.com/vaadin/starters/files/10367326/workhours-vaadin23.zip)
![image](https://user-images.githubusercontent.com/19290633/211173093-4f05c94a-2b48-4e3d-8195-cc3a3e8bced7.png)
2. Open in IDEA and navigate to AbstractEntity

**Expected behavior**
No errors

**Comment by MarcinVaadin** [comment]
Dependency has been added. Thanks for spotting the issue.
