### ISSUE TITLE
Jdk 8 support in starters

### ISSUE THREAD

**Issue by mikhailusachev** [vaadin/starters#109]
I'm always frustrated when i am unable to run my favorite app on windows xp

**Describe the solution you'd like**
I'd like to have a solution to build against jdk 8 in any starter

![Снимок экрана 2023-01-19 в 10 38 04](https://user-images.githubusercontent.com/6051032/213382996-c5317a96-0661-493b-ac71-79e6e78fe8a2.png)

**Comment by Artur-** [comment]
A Vaadin 14 starter can be found from https://vaadin.com/hello-world-starters. That one supports Java 8

**Comment by samie** [comment]
To help finding the right ones, I added a note to V14 projects that use Java 8. https://vaadin.com/hello-world-starters#v14

**Comment by mikhailusachev** [comment]
Just to let you know @samie and @Artur- 
i just downloaded starter for V22 and it's configured for java 1.8, so 22.0.27 seems to be the last version supporting java 8
