### ISSUE TITLE
Restore the link to the page of alternative starter downloads (Plain Servlet, etc.)

### ISSUE THREAD

**Issue by Basil-Dot-Work** [vaadin/starters#110]
**Is your feature request related to a problem? Please describe.**

I cannot find the download links for your other alternative starters for non-Spring based Vaadin Flow projects.

**Describe the solution you'd like**

Restore the link you used to have on your https://start.vaadin.com/app web app leading to the page listing other starter downloads.

**Additional context**

FYI, your current setup makes it look like Vaadin Flow requires Spring. That can be a turn off for many of us. Not everybody uses Spring.

**Comment by tarekoraby** [comment]
The links are available at https://vaadin.com/hello-world-starters.

**Comment by tarekoraby** [comment]
> FYI, your current setup makes it look like Vaadin Flow requires Spring. That can be a turn off for many of us. Not everybody uses Spring

Thanks for the feedback! We will consider what can be done to improve this situation.

**Comment by emarc** [comment]
Hi,

The new https://start.vaadin.com has a section called "Hello World Project" where you can get a starter project with a different tech stack. 

![Start-alt-stack](https://github.com/vaadin/starters/assets/7479/10c5056c-174d-46ae-9891-c6ca05b0e7eb)

Press the "Edit" button to choose from the combinations.

![choose-stack](https://github.com/vaadin/starters/assets/7479/9f21eaa1-4422-4684-8e7e-9bf0904ea50c)

I think this addresses your need, but let us know if something is still missing!
