### ISSUE TITLE
Rich Text Editor view fails to compile

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/starters#111]
A project with the RTE template fails to compile. It generates a `RichTextRichTextEditorView` class inside a `RichTextEditorView.java` file.

**Comment by Artur-** [comment]
Is this only with some special name for the view?

**Comment by tarekoraby** [comment]
I'm using the default one. 
![image](https://user-images.githubusercontent.com/42799254/224566389-ad9c9bd8-63d2-4b02-84f8-86b8f72d46e6.png)

**Comment by tarekoraby** [comment]
Removing "editor" from the name doesn't produce the issue.

**Comment by MarcinVaadin** [comment]
Cannot reproduce on current start.vaadin.com, please reopen if needed.
