### ISSUE TITLE
Theme not being applied to fresh project

### ISSUE THREAD

**Issue by MrDraqon** [vaadin/starters#113]
**Describe the bug**

**To Reproduce**
1. Use Vaadin Starter 'Make a new project with the starter customize the theme'
2. Download 'Project'
3. Run 'once downloaded unzip it and run it,'

**Expected behavior**
I expected the theme settings i added to work, but its the default light theme
Checked the style files and the settings i added are there but the app still shows up in light mode

**Environment (please complete the following information):**
 - Starter name myapp
 - OS: [e.g. Windows]
 - Vaadin latest

**Additional context**
i didnt modify the project only pressed intellijs run button the @Theme annotation is present with folder name and Variant name.
100% fresh project from vaadin starter didnt add anything other than modifying theme settings

**Comment by jouni** [comment]
Thanks for the report! This is the issue you should follow: https://github.com/vaadin/flow/issues/16256
