### ISSUE TITLE
Problem creating new starter

### ISSUE THREAD

**Issue by rahff** [vaadin/starters#116]
I was unable to download my application from start.vaadin.com.

This was the configuration used:

``{
  "applicationConfiguration": {
    "projectName": "My App",
    "groupId": "com.example.application",
    "vaadinVersion": "v24",
    "codeGeneration": "JAVA",
    "dockerConfiguration": false,
    "kubernetesConfiguration": false,
    "alwaysGenerateBackend": false,
    "javaVersion": 17,
    "access": "PUBLIC",
    "experimentalFeatures": [],
    "git": true,
    "runOnRandomPort": false,
    "generatedProjectId": "e38b23ec-0722-4ffd-bf74-6ab5476a3d5a"
  },
  "theme": {
    "componentStyles": {},
    "variant": "light",
    "styles": ""
  },
  "views": [
    {
      "name": "Main",
      "type": "menu-on-left-layout",
      "route": "",
      "entityId": -1,
      "children": [
        {
          "id": 3,
          "name": "Card List",
          "type": "card-list-view",
          "route": "card-list",
          "icon": "list-solid",
          "entityId": -1,
          "children": [],
          "generateTestData": true,
          "generateUrlTemplate": false
        },
        {
          "id": 4,
          "name": "",
          "type": "hello-world-view",
          "route": "",
          "icon": "globe-solid",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 6,
          "name": "Chat",
          "type": "chat-view",
          "route": "chat",
          "icon": "comments",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 7,
          "name": "Checkout Form",
          "type": "checkout-form-view",
          "route": "checkout-form",
          "icon": "credit-card",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 8,
          "name": "Empty",
          "type": "empty-view",
          "route": "empty",
          "icon": "file",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 9,
          "name": "Person Form",
          "type": "person-form-view",
          "route": "person-form",
          "icon": "user",
          "entityId": 1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 10,
          "name": "Image List",
          "type": "image-list-view",
          "route": "image-list",
          "icon": "th-list-solid",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 11,
          "name": "Grid with Filters",
          "type": "grid-with-filters-view",
          "route": "grid-with-filters",
          "icon": "filter-solid",
          "entityId": 1,
          "children": [],
          "generateTestData": true,
          "generateUrlTemplate": false
        }
      ],
      "generateTestData": false,
      "generateUrlTemplate": false,
      "id": 0
    }
  ],
  "entities": [
    {
      "id": 1,
      "name": "SamplePerson",
      "fields": [
        {
          "name": "id",
          "dataType": "ID",
          "editorType": "vaadin-text-field",
          "fieldType": "Integer",
          "uiType": "Text",
          "validators": [
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "firstName",
          "dataType": "FIRST_NAME",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "lastName",
          "dataType": "LAST_NAME",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "email",
          "dataType": "EMAIL",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "jakarta.validation.constraints.Email",
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "phone",
          "dataType": "PHONE_NUMBER",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "dateOfBirth",
          "dataType": "DATE_OF_BIRTH",
          "editorType": "vaadin-date-picker",
          "fieldType": "LocalDate",
          "uiType": "Text",
          "validators": [
            "jakarta.annotation.Nullable"
          ]
        },
        {
          "name": "occupation",
          "dataType": "OCCUPATION",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "role",
          "dataType": "WORK_ROLE",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "dev.hilla.Nonnull"
          ]
        },
        {
          "name": "important",
          "dataType": "BOOLEAN_10_90",
          "editorType": "vaadin-checkbox",
          "fieldType": "boolean",
          "uiType": "Checkbox",
          "validators": []
        }
      ]
    }
  ]
}

```

**Comment by MarcinVaadin** [comment]
`"name": "",` - name cannot be empty, thank you for spotting, validation will be added soon.
