### ISSUE TITLE
Eat your own dog food ;-)

### ISSUE THREAD

**Issue by chrisw73** [vaadin/starters#122]
I would highly recomment to offer the generated sources as a combination of typescript/Lit templates and java companion files.
Pure java files are Vaadin of the 2000nds and should not be promoted anymore in my humble opinion.

**Comment by Artur-** [comment]
Thanks, we eat it on a daily basis. 

If you want a Lit + Java combination you can select one of the "for Designer" templates in start.vaadin.com. If you want even more TypeScript/HTML and less Java, check out https://hilla.dev/ and the Hilla CLI

**Comment by chrisw73** [comment]
Bon appetit!
IMHO it should be default and more exposed, so that guys with glasses - as I am ;-) - can find them. In Addition IMHO the template files are "not only for "with Designer"" but more for "cleaner code" and deviding controller code in Java an UI/UX in template files.

**Comment by tarekoraby** [comment]
> IMHO the template files are "not only for "with Designer"" but more for "cleaner code" and deviding controller code in Java an UI/UX in template files.

Thanks for the feedback. We are glad that you find the template-based approach useful, and we will continue to support and enhance this mode moving forward. However, Vaadin Flow remains primarily aimed at serving the needs of those who want to develop their views (or at least most of their views) in pure Java, without touching JS or TS.

**Comment by chrisw73** [comment]
Thanks. Marketing should be more focused on the most productive way... Which is neither of the more promoted or popular (Hilla and pure Java)...

**Comment by tarekoraby** [comment]
Thanks. We take your feedback on board.

**Comment by samie** [comment]
> Thanks. Marketing should be more focused on the most productive way... Which is neither of the more promoted or popular (Hilla and pure Java)...

Only now saw this one, and if not about this issue in starters, but I'm still really interested in hearing more.

@chrisw73 Do you have a good (small) example you consider productive way of working, with Vaadin? 

To me this is not one one-size-fits-all, and I wrote about different [component architectures and their pros/cons](https://dev.to/samiekblad/whats-the-deal-with-vaadin-add-ons-2f1n). The title is about "add-ons" and "components", but in Vaadin everything i UI is a component, so...
