### ISSUE TITLE
routes.tsx should not contain "requiresLogin: true" for /login path

### ISSUE THREAD

**Issue by taefi** [vaadin/starters#129]
**Describe the bug**
When generating a Hilla application using `--auth` flag, it adds an unnecessary `requiresLogin: true` in the `routes.tsx` for the `LoginView` as well.

Although, the `requiresLogin: true` is a sort of meta-data for the router and does not affect the functionality (the login form is being displayed properly), it is not needed and causes confusions for the users.

**To Reproduce**
1. Use `npx @hilla/cli init --react --auth hilla-with-auth` to create a Hilla app with security
2. Open `frontend/routes.tsx` 
3. Locate the path `/login` in the list of routes

**Expected behavior**
The `/login` path should not contain `requiresLogin: true`.

**Comment by Artur-** [comment]
I don't think it does anymore
