### ISSUE TITLE
Visual View Builder: Can't add to the bottom if I fake a FormLayout

### ISSUE THREAD

**Issue by bennewi** [vaadin/starters#132]
**To Reproduce**
1) on Visual View Builder, create a horizontal layout
2) put two vertical layouts in the horizontal layout
3) put a bunch of components in both vertical layouts so they overflow the editing area
4) now put a grid at the bottom of one of the vertical layouts
5) now I'm not able to add anything below the grid

**Screenshots**
![image](https://github.com/vaadin/starters/assets/19489804/6f7b4a1a-54e8-4f97-8c42-ca01ef6cfe95)

**Environment (please complete the following information):**
Windows, Chrome

**Comment by MarcinVaadin** [comment]
Known issue, you just need to scroll outermost scrollbar to bottom of the view, then the slot will be visible.

**Comment by bennewi** [comment]
I don't think you have succeeded to reproduce the problem @MarcinVaadin 

Here is my situation, with the outermost scrollbar all the way at the bottom

<img width="1906" alt="image" src="https://github.com/vaadin/starters/assets/19489804/9567c967-3792-4e87-97a0-ab6cfb0f7c6e">

now when I start dragging a new component, the content gets shifted down because of all of the drop zones that appear. I cannot scroll the outer scrollbar down to put it at the end

<img width="1890" alt="image" src="https://github.com/vaadin/starters/assets/19489804/e710a693-89b7-4316-84dc-ad6254335a84">


Because I'm in the middle of a drag and drop, my mouse is not available to scroll down further

**Comment by MarcinVaadin** [comment]
Issue reproducible, can be checked on https://start.vaadin.com/app?id=afd7bbe2-3450-4e12-b9af-d2c2e2659c08

Problem is that automatic scrolling of viewport when moving mouse pointer to edge of the view suddenly stops or even don't work at all.

**Comment by jouni** [comment]
The automatic scroll works in Firefox. Also works in Chrome, as long as you remove the 100% height from the root layout. Then you should be able to keep the mouse pointer at the bottom of the view and Chrome scrolls to the bottom for you.

Safari (still) doesn't seem to automatically scroll containers during a drag operation.

I don't think it matters what type of layouts or components you put in the view. Just the fact that the root layout is 100% high and the contents in it are overflowing beyond that.

**Comment by abdullahtellioglu** [comment]
I implemented a `dragover` listener to detect pointer position and depending on the position I scroll manually in the listener if the pointer is at the bottom or top of the container. In my opinion, this solution is easier to scroll bottom or top while dragging. What do you think @jouni ?

**Comment by jouni** [comment]
Sure, if we already have a working fix, that’s great. Just wanted to point out certain aspects of this issue.
