### ISSUE TITLE
Problem creating new starter

### ISSUE THREAD

**Issue by hyornsenn** [vaadin/starters#146]
I was unable to download my application from start.vaadin.com.

This was the configuration used:

{
  "applicationConfiguration": {
    "projectName": "CRM AParts",
    "groupId": "com.crm.application",
    "vaadinVersion": "v24",
    "codeGeneration": "JAVA",
    "dockerConfiguration": false,
    "kubernetesConfiguration": false,
    "alwaysGenerateBackend": true,
    "javaVersion": 17,
    "access": "PUBLIC",
    "experimentalFeatures": [],
    "git": false,
    "runOnRandomPort": false,
    "artifactId": "a-part-crm",
    "packageManager": "NPM",
    "database": "H2",
    "generatedProjectId": "06df26f8-d1b9-4da7-953e-2052bdfd4dcb"
  },
  "theme": {
    "componentStyles": {},
    "variant": "dark",
    "styles": "    html {\n      --lumo-shade-5pct: rgba(33, 33, 33, 0.05);\n      --lumo-shade-10pct: rgba(33, 33, 33, 0.1);\n      --lumo-shade-20pct: rgba(33, 33, 33, 0.2);\n      --lumo-shade-30pct: rgba(33, 33, 33, 0.3);\n      --lumo-shade-40pct: rgba(33, 33, 33, 0.4);\n      --lumo-shade-50pct: rgba(33, 33, 33, 0.5);\n      --lumo-shade-60pct: rgba(33, 33, 33, 0.6);\n      --lumo-shade-70pct: rgba(33, 33, 33, 0.7);\n      --lumo-shade-80pct: rgba(33, 33, 33, 0.8);\n      --lumo-shade-90pct: rgba(33, 33, 33, 0.9);\n      --lumo-primary-color-50pct: rgba(235, 89, 5, 0.5);\n      --lumo-primary-color-10pct: rgba(235, 89, 5, 0.1);\n      --lumo-error-color-50pct: rgba(231, 24, 24, 0.5);\n      --lumo-error-color-10pct: rgba(231, 24, 24, 0.1);\n      --lumo-success-color-50pct: rgba(62, 229, 170, 0.5);\n      --lumo-success-color-10pct: rgba(62, 229, 170, 0.1);\n      --lumo-shade: hsl(0, 0%, 13%);\n      --lumo-primary-color: hsl(22, 96%, 47%);\n      --lumo-primary-text-color: hsl(22, 100%, 42%);\n      --lumo-error-color: hsl(0, 81%, 50%);\n      --lumo-error-text-color: hsl(0, 86%, 45%);\n      --lumo-success-color: hsl(159, 76%, 57%);\n      --lumo-success-contrast-color: hsl(159, 29%, 10%);\n      --lumo-success-text-color: hsl(159, 61%, 40%);\n\n    }\n"
  },
  "views": [
    {
      "name": "Main",
      "type": "menu-on-top-layout",
      "route": "",
      "entityId": -1,
      "children": [
        {
          "name": "About",
          "type": "empty-view",
          "route": "about",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false,
          "icon": "birthday-cake-solid",
          "id": 2,
          "access": ""
        },
        {
          "id": 4,
          "name": "LRAreasView",
          "type": "custom-view",
          "route": "LRAreasView",
          "icon": "pencil-ruler-solid",
          "entityId": 1,
          "access": "PUBLIC",
          "children": [],
          "generateTestData": true,
          "generateUrlTemplate": false,
          "componentModel": {
            "type": "layout-column",
            "parameters": {
              "mainLength": "100%",
              "crossLength": "100%",
              "gap": "m",
              "padding": "m"
            },
            "children": []
          }
        },
        {
          "id": 6,
          "name": "Chat",
          "type": "chat-view",
          "route": "chat",
          "icon": "comments",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 7,
          "name": "Image Gallery",
          "type": "image-list-view",
          "route": "image-gallery",
          "icon": "th-list-solid",
          "entityId": -1,
          "access": "ADMIN_ROLE",
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 8,
          "name": "Credit Card Form",
          "type": "credit-card-form-view",
          "route": "credit-card-form",
          "icon": "credit-card",
          "entityId": -1,
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 9,
          "name": "Person Form",
          "type": "person-form-view",
          "route": "person-form",
          "icon": "user",
          "entityId": 1,
          "access": "PUBLIC",
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false,
          "componentModel": {
            "children": [
              {
                "type": "layout-row",
                "parameters": {
                  "crossLength": "100%"
                },
                "children": [
                  {
                    "type": "layout-column",
                    "parameters": {
                      "mainLength": "100%"
                    }
                  },
                  {
                    "type": "layout-column",
                    "parameters": {
                      "mainLength": "100%",
                      "gap": "m"
                    },
                    "children": [
                      {
                        "parameters": {
                          "text": "Personal Information"
                        },
                        "type": "h3"
                      },
                      {
                        "parameters": {
                          "crossLength": "100%",
                          "gap": "l"
                        },
                        "type": "layout-row",
                        "children": [
                          {
                            "parameters": {
                              "gap": "m",
                              "mainLength": "100%"
                            },
                            "type": "layout-column",
                            "children": [
                              {
                                "parameters": {
                                  "label": "First Name",
                                  "crossLength": "100%"
                                },
                                "type": "text-field"
                              },
                              {
                                "parameters": {
                                  "label": "Birthday",
                                  "crossLength": "100%"
                                },
                                "type": "date-picker"
                              },
                              {
                                "parameters": {
                                  "label": "Email",
                                  "crossLength": "100%"
                                },
                                "type": "email-field"
                              }
                            ]
                          },
                          {
                            "parameters": {
                              "mainLength": "100%",
                              "gap": "m"
                            },
                            "type": "layout-column",
                            "children": [
                              {
                                "parameters": {
                                  "label": "Last Name",
                                  "crossLength": "100%"
                                },
                                "type": "text-field"
                              },
                              {
                                "parameters": {
                                  "gap": "m",
                                  "crossLength": "100%"
                                },
                                "type": "layout-row",
                                "children": [
                                  {
                                    "parameters": {
                                      "label": "Phone Number",
                                      "mainLength": "100%"
                                    },
                                    "type": "text-field"
                                  }
                                ]
                              },
                              {
                                "parameters": {
                                  "label": "Occupation",
                                  "crossLength": "100%"
                                },
                                "type": "text-field"
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "parameters": {
                          "gap": "m"
                        },
                        "type": "layout-row",
                        "children": [
                          {
                            "parameters": {
                              "text": "Save"
                            },
                            "type": "button-primary"
                          },
                          {
                            "parameters": {
                              "text": "Cancel"
                            },
                            "type": "button-secondary"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "type": "layout-column",
                    "parameters": {
                      "mainLength": "100%",
                      "gap": "m"
                    }
                  }
                ]
              }
            ],
            "default": {
              "type": "layout-column",
              "parameters": {
                "crossLength": "100%",
                "padding": "l"
              },
              "children": [
                {
                  "type": "layout-row",
                  "parameters": {
                    "crossLength": "100%"
                  },
                  "children": [
                    {
                      "type": "layout-column",
                      "parameters": {
                        "mainLength": "100%"
                      }
                    },
                    {
                      "type": "layout-column",
                      "parameters": {
                        "mainLength": "100%",
                        "gap": "m"
                      },
                      "children": [
                        {
                          "parameters": {
                            "text": "Personal Information"
                          },
                          "type": "h3"
                        },
                        {
                          "parameters": {
                            "crossLength": "100%",
                            "gap": "l"
                          },
                          "type": "layout-row",
                          "children": [
                            {
                              "parameters": {
                                "gap": "m",
                                "mainLength": "100%"
                              },
                              "type": "layout-column",
                              "children": [
                                {
                                  "parameters": {
                                    "label": "First Name",
                                    "crossLength": "100%"
                                  },
                                  "type": "text-field"
                                },
                                {
                                  "parameters": {
                                    "label": "Birthday",
                                    "crossLength": "100%"
                                  },
                                  "type": "date-picker"
                                },
                                {
                                  "parameters": {
                                    "label": "Email",
                                    "crossLength": "100%"
                                  },
                                  "type": "email-field"
                                }
                              ]
                            },
                            {
                              "parameters": {
                                "mainLength": "100%",
                                "gap": "m"
                              },
                              "type": "layout-column",
                              "children": [
                                {
                                  "parameters": {
                                    "label": "Last Name",
                                    "crossLength": "100%"
                                  },
                                  "type": "text-field"
                                },
                                {
                                  "parameters": {
                                    "gap": "m",
                                    "crossLength": "100%"
                                  },
                                  "type": "layout-row",
                                  "children": [
                                    {
                                      "parameters": {
                                        "label": "Phone Number",
                                        "mainLength": "100%"
                                      },
                                      "type": "text-field"
                                    }
                                  ]
                                },
                                {
                                  "parameters": {
                                    "label": "Occupation",
                                    "crossLength": "100%"
                                  },
                                  "type": "text-field"
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "parameters": {
                            "gap": "m"
                          },
                          "type": "layout-row",
                          "children": [
                            {
                              "parameters": {
                                "text": "Save"
                              },
                              "type": "button-primary"
                            },
                            {
                              "parameters": {
                                "text": "Cancel"
                              },
                              "type": "button-secondary"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "type": "layout-column",
                      "parameters": {
                        "mainLength": "100%",
                        "gap": "m"
                      }
                    }
                  ]
                }
              ]
            },
            "parameters": {
              "crossLength": "100%",
              "padding": "l"
            },
            "type": "layout-column"
          }
        },
        {
          "id": 10,
          "name": "Master-Detail",
          "type": "master-detail-view",
          "route": "master-detail",
          "icon": "columns-solid",
          "entityId": 1,
          "access": "ADMIN_ROLE",
          "children": [],
          "generateTestData": true,
          "generateUrlTemplate": true
        },
        {
          "id": 11,
          "name": "Address Form",
          "type": "address-form-view",
          "route": "address-form",
          "icon": "map-marker-solid",
          "entityId": 2,
          "access": "ADMIN_ROLE",
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 12,
          "name": "Checkout Form",
          "type": "checkout-form-view",
          "route": "checkout-form",
          "icon": "credit-card",
          "entityId": -1,
          "access": "ADMIN_ROLE",
          "children": [],
          "generateTestData": false,
          "generateUrlTemplate": false
        },
        {
          "id": 13,
          "name": "Grid with Filters",
          "type": "grid-with-filters-view",
          "route": "grid-with-filters",
          "icon": "filter-solid",
          "entityId": 1,
          "access": "ADMIN_ROLE",
          "children": [],
          "generateTestData": true,
          "generateUrlTemplate": false
        }
      ],
      "generateTestData": false,
      "generateUrlTemplate": false,
      "id": 0
    }
  ],
  "entities": [
    {
      "id": 1,
      "name": "SamplePerson",
      "fields": [
        {
          "name": "id",
          "dataType": "ID",
          "editorType": "vaadin-text-field",
          "fieldType": "Integer",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "firstName",
          "dataType": "FIRST_NAME",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "lastName",
          "dataType": "LAST_NAME",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "email",
          "dataType": "EMAIL",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": [
            "jakarta.validation.constraints.Email"
          ]
        },
        {
          "name": "phone",
          "dataType": "PHONE_NUMBER",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "dateOfBirth",
          "dataType": "DATE_OF_BIRTH",
          "editorType": "vaadin-date-picker",
          "fieldType": "LocalDate",
          "uiType": "Text",
          "validators": [
            "jakarta.annotation.Nullable"
          ]
        },
        {
          "name": "occupation",
          "dataType": "OCCUPATION",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "role",
          "dataType": "WORK_ROLE",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "important",
          "dataType": "BOOLEAN_10_90",
          "editorType": "vaadin-checkbox",
          "fieldType": "boolean",
          "uiType": "Checkbox",
          "validators": []
        }
      ]
    },
    {
      "id": 2,
      "name": "SampleAddress",
      "fields": [
        {
          "name": "id",
          "dataType": "ID",
          "editorType": "vaadin-text-field",
          "fieldType": "Integer",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "street",
          "dataType": "ADDRESS",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "postalCode",
          "dataType": "ZIP_CODE",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "city",
          "dataType": "CITY",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "state",
          "dataType": "STATE",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "country",
          "dataType": "COUNTRY",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        }
      ]
    },
    {
      "id": 5,
      "name": "User",
      "fields": [
        {
          "name": "id",
          "dataType": "ID",
          "editorType": "vaadin-text-field",
          "fieldType": "Integer",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "username",
          "dataType": "FIRST_NAME",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "name",
          "dataType": "FULL_NAME",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "hashedPassword",
          "dataType": "TWO_WORDS",
          "editorType": "vaadin-text-field",
          "fieldType": "Password",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "roles",
          "dataType": "WORD",
          "editorType": "vaadin-text-field",
          "fieldType": "String",
          "uiType": "Text",
          "validators": []
        },
        {
          "name": "profilePicture",
          "dataType": "PROFILE_PICTURE_URL",
          "editorType": "vaadin-upload",
          "fieldType": "ImageData",
          "uiType": "Image",
          "validators": [],
          "uiHints": {
            "gridColumnWidth": "96px",
            "height": "MEDIUM",
            "roundImage": true
          }
        }
      ]
    }
  ]
}
```

**Comment by MarcinVaadin** [comment]
Issue assigned for investigation

**Comment by MarcinVaadin** [comment]
Same issue as in https://github.com/vaadin/starters/issues/157, fix implemented, will be released today.
