### ISSUE TITLE
starter breaks if text contain " (quotation mark)

### ISSUE THREAD

**Issue by Ben1902** [vaadin/starters#149]
**Describe the bug**
If a text in the design contain one or more quotation marks, the export does not work

**To Reproduce**
Include a text in your mock-up, and edit the text. Paste letters with a set of quotation marks inside it

**Expected behavior**
Quotation marks should be escaped server side, or encoded somehow, and not break any code

**Environment (please complete the following information):**
 - Starter online (WEB, https://start.vaadin.com/)
 - Browser: Chrome

**Comment by MarcinVaadin** [comment]
Issue assigned for investigation

**Comment by MarcinVaadin** [comment]
Fixed, updated version deployed, thank you for feedback!
