### ISSUE TITLE
Secured Spring Starter should work with the Upload

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/starters#15]
**Describe the bug**
If I put an Upload and try to get the security context, the security context will return null.

**To Reproduce**
Add this code in the Full Stack App and try to upload a document:
```
Upload upload = new Upload(memoryBuffer);
		upload.addSucceededListener(e -> {
			System.out.println("sdsd" + SecurityUtils.getUsername());
		});
```
**Expected behavior**
The username should be set for the Upload listener.

Here is the explanation: https://vaadin.com/learn/tutorials/securing-your-app-with-spring-security/speciale#_can_you_trust_vaadin_upload

In 
This line should be added in configure:
```
.antMatchers("/VAADIN/**").permitAll()
```
And it should be removed from the ignore list.

**Comment by anasmi** [comment]
Hi,

thank you for reporting an issue! As this is an additional feature (even if an easy to implement) of accessing SecurityContext from a `VAADIN` static requests, I removed the `bug` label and marked the issue as an enhancement.

**Comment by anasmi** [comment]
Easy to implement, but not sure if we would like to add it as proper explanation is than needed

**Comment by jcgueriaud1** [comment]
I think this starter is used by our customers to make the Vaadin default configuration, then few times later when they need the user details in the upload listener or the Resource (to download a generated file) they have an unexpected error.

It's hard to make the connection between the error and the security configuration. Especially if the official sample is "wrong".
It could also be a comment with the link to the documentation.

Perhaps this default configuration should be reviewed by someone, to be sure that it won't add any security issues.

**Comment by anasmi** [comment]
I am not against the idea, sure. And I see the point. I just can't promise we will do it tomorrow :)

**Comment by samie** [comment]
Applies also to OAuth example: https://github.com/vaadin/vaadin-oauth-example

**Comment by Artur-** [comment]
Is this fixed with the V20 security configuration?

**Comment by jcgueriaud1** [comment]
I didn't try the V20 version.  Maybe it can be tested during our PiT.
From the PR I read I think it should be ok.

**Comment by Artur-** [comment]
At least V21 fixes this
