### ISSUE TITLE
Scope custom text field styling to a single instance

### ISSUE THREAD

**Issue by jouni** [vaadin/starters#16]
The custom styling for text fields, which is done for example in the [skeleton-starter-flow-spring](https://github.com/vaadin/skeleton-starter-flow-spring/blob/master/frontend/styles/vaadin-text-field-styles.css), end up affecting all text fields. 

Since our internal developers also use the official starters to do all kinds of things, there’s a high risk of those customized styles ending up in screenshots in various places, such as our documentation ([example](https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/getting-started/getting-started-kotlin.asciidoc#example-project-walkthrough)). But since the styling is not actually the default, it can cause small annoyances for users when if they start with something else that doesn’t include the same style customizations. 

Instead of making the style customization global (affecting all text fields), we should scope it with a theme variant.

Before:
```css
[part="input-field"] {
  ...
}
```

After:
```css
:host([theme~="bordered"]) [part="input-field"] {
  ...
}
```

And in Java, before: 
```java
TextField textField = new TextField("Your name");
```

After: 
```java
TextField textField = new TextField("Your name");
textField.getThemeNames().add("bordered");
```

**Comment by samie** [comment]
Update the explanation comment in stylesheet.

**Comment by anasmi** [comment]
- Done in starter-flow-spring (The PR : https://github.com/vaadin/skeleton-starter-flow-spring/pull/363)

**Comment by anasmi** [comment]
The pull requests were merged and correct files should be available to the users. I will close this ticket as resolved. Thank you for the detailed description on how to address the problem! :)
