### ISSUE TITLE
vaadin-localization-example demo instance throws an error

### ISSUE THREAD

**Issue by manolo** [vaadin/starters#17]
**Describe the bug**
Demo app is not working

**To Reproduce**
Just visit https://vaadin-localization-example.herokuapp.com/

**Expected behavior**
App should work and not show any error

**Screenshots**
<img width="1069" alt="Screenshot 2020-08-17 at 14 47 25" src="https://user-images.githubusercontent.com/161853/90397747-9b195180-e098-11ea-86c1-08cea6ccf4b9.png">

**Environment (please complete the following information):**
Chrome

**Additional context**
There is a link from https://vaadin.com/start

**Comment by samie** [comment]
When was this occurring? Are you able to reproduce it? We redeployed the app on Aug 13 for the same reason and the bug itself has been fixed already on Jul 9, 2020.

**Comment by samie** [comment]
I'm closing this one. Does not seem to happen anymore.
