### ISSUE TITLE
iron-icon not visible in production mode with a Master-Detail view from start.vaadin.com

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/starters#20]
When I download the starter with a master-detail view. The icons in the columns are not visible.

https://stackoverflow.com/questions/68348596/the-iron-icon-not-visible-with-a-master-detail-view-generate-with-vaadin-app-sta/68373324#68373324

I choose Flow, then Add a master detail view. Here the attached project.
[test-icon.zip](https://github.com/vaadin/starters/files/6814151/test-icon.zip)

The reason is that the Vaadin icon is not used in the application (only in the renderer) so it's not in the bundle. Adding this is solving the issue:
`@Uses(Icon.class)`

**Comment by Artur-** [comment]
Can't reproduce the problem with the given zip. I do see the problem with a V21 project though but the cause seems to be different

**Comment by jcgueriaud1** [comment]
Sorry I forgot to mention that you need to run it in production mode. In "dev" mode, it's working.

Did you try in production mode?

**Comment by Artur-** [comment]
Could you verify that this works now?

**Comment by jcgueriaud1** [comment]
Sorry for the late answer. Yes it's working
