### ISSUE TITLE
when making changes to themes and having the setting "No menu", the theme will NOT be applied in the downloaded project

### ISSUE THREAD

**Issue by F0rce** [vaadin/starters#22]
**Describe the bug**
This bug is related to https://start.vaadin.com when creating and personalizing a flow starter (14.6.8).

**To Reproduce**
1. Open https://start.vaadin.com
2. Choose Flow
3. Create a single view -> Name: ThemeBug, URL: "" (none), Template: Card List
4. Change Theme Settings -> Color - Mode: Dark; Typography - Font: Roboto Mono; Style - Roundness: Most Round
5. Change Settings -> Menu: No Menu
6. Download the project -> unzip it -> mvn clean install -> mvn spring-boot:run and open localhost:8080/

**Expected behavior**
![Screenshot 2021-08-20 133108](https://user-images.githubusercontent.com/60381251/130226925-9bb48254-0ce5-43a3-b033-1ec4eb8607d9.png)

**Actual behavior**
![Bildschirmfoto 2021-08-19 um 21 09 07](https://user-images.githubusercontent.com/60381251/130227030-2747b882-cb53-4191-a236-9fa6c0721662.png)

**Environment (please complete the following information):**
 - Flow Starter 
 - OS: Windows (and tested on mac)
 - Browser chrome, mozilla, safari
 - Vaadin version 14.6.8

**Additional context**
After speaking to support, this is happening because with the "no menu" selection there is no main layout.
To Fix it you just have to add in your ThemeBug view the annotation `@Theme(themeFolder = "themebug", variant = Lumo.DARK).`

**Comment by Artur-** [comment]
This was broken for Vaadin 14 where the theme is specified on the main layout. Now it is specified on the first view
