### ISSUE TITLE
Vaadin 21 allows to view login view even if user is already authenticated

### ISSUE THREAD

**Issue by XakepSDK** [vaadin/starters#29]
### Description of the bug / feature
Vaadin let's open login view even if user is logged in

### Minimal reproducible example
Create vaadin 21 project with security here: https://start.vaadin.com/

### Expected behavior
Vaadin does not allow to view login view if user is already logged in

### Actual behavior
Vaadin allows to view login view even if user is already logged in

### Versions:
    - Vaadin / Flow version: 21.0.2

### Suggestion
I guess it can be fixed with a check here: https://github.com/vaadin/flow/blob/0752695154e5041102221a7ba7002778d122cf3f/flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java#L156
Check if user is already authenticated and tries to visit login view

**Comment by pleku** [comment]
While I do agree that it is probably not something that is needed (be able to open login view when logged in), I don't see how/why the login view should be disabled by the default ViewAccessControl. It would be weird too if opening the login view would give an "access denied" exception when you are logged in. Maybe there should be some redirect or something instead.

I misinterpreted the situation before looking at the code and moved this to the starter issue tracking, but not sure if there really should be something done in /flow or if this should be just handled in the starter project instead. Views can be dynamically registered and unregistered but I have not tested how that plays with the view access control. So basically for login, just remove the login view from the session based route storage and then add it back on logout. More details in https://vaadin.com/docs/v21/flow/routing/dynamic

**Comment by pleku** [comment]
Another option would be that the login view itself handles the redirect if someone tries to open it when user is logged in already. That should be probably done in the starter and also showcased in the /flow/security docs.

**Comment by Artur-** [comment]
Sounds like it could make sense to redirect from the login view to the default login URL if the user is logged in

**Comment by tarekoraby** [comment]
The login view is now changed to redirect to the default URL if the user is logged in. Thanks for the report @XakepSDK.

**Comment by dk2k** [comment]
> The login view is now changed to redirect to the default URL if the user is logged in. Thanks for the report @XakepSDK.

what do I need to do to have this behavior in my vaadin flow app?
