### ISSUE TITLE
Can't execute `integration-tests` profile in some starters

### ISSUE THREAD

**Issue by qtdzz** [vaadin/starters#3]
**Describe the bug**
`drivers.xml` is not included in the downloaded starter so the `integration-tests` profiles can't be used

**To Reproduce**
1. Download Spring boot/CDI and Java EE/ Plain Java Servlet starter
2. Run `mvn install -Pintegration-test`
3. See error

**Expected behavior**
It should execute integration tests

**Actual behavior**
The command fails because `drivers.xml` is missing from the project directory

**Environment (please complete the following information):**
 - Spring boot/CDI and Java EE/ Plain Java Servlet in v14 (probably in v13 as well)
 - OS: Linux
 - Browser: N/A
 - Vaadin version: 14.0.0.rc9

**Additional context**
As @alvarezguille pointed out, `webdrivers.xml` is allowed but not `drivers.xml`. The starters are using `drivers.xml` while bakery is using `webdrivers.xml`.  That's why bakery is still fine but not the others.

**Comment by anasmi** [comment]
Related : https://github.com/vaadin/skeleton-starter-flow-spring/pull/348

**Comment by anasmi** [comment]
The problem was verified in the BAS and we should now change from the `webdrivers.xml` to use the https://github.com/bonigarcia/webdrivermanager library. We have created an internal ticket for it at https://github.com/vaadin/90min-dx-tasks/issues/184.

Thank you for reporting the issue!

**Comment by anasmi** [comment]
This should be fixed by now in the all starters by using webdriver manager instead of the manually managing `drivers.xml`
