### ISSUE TITLE
Allow to switch Git of

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#31]
start.vaadin.com adds Git to the generated project.

For me this is not convenient because I usually create a git project first and then copy the code from the generated Vaadin project.

Please add an option in the settings to turn off Git.
Thank you

**Comment by tarekoraby** [comment]
Fixed. Vaadin Start settings now have a Git flag.

**Comment by simasch** [comment]
Thank you @tarekoraby !

**Comment by tarekoraby** [comment]
You're very welcome @simasch! 
Thank you very much for the suggestion 😄
