### ISSUE TITLE
Access Control Settings may lead to Access Denied after login

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#33]
If I set the "Hello World" (or any other view that is in the first place) to "Users with the user role" then after successful login I'll get

```
Could not navigate to ''
Reason: Access denied

Available routes:
about
hello
login
This detailed message is only shown when running in development mode.
```

IMHO this is very confusing for inexperienced developers. 

Why doesn't the admin user have also the user role?

**Comment by tarekoraby** [comment]
I agree. Admins are usually considered normal users. We will change the roles in the starters accordingly.

**Comment by Artur-** [comment]
Now at https://start.vaadin.com
