### ISSUE TITLE
Use . instead of / in whitelisted packages

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#34]
The starter generates 

`vaadin.whitelisted-packages = com/vaadin,org/vaadin,io/seventytwo/demo`

IMHO this confuses developers because packages are using . not / and the property is named whitelisted-packages and not whitelisted-folders.

So it would be much more clear to have it generated like this:

`vaadin.whitelisted-packages = com.vaadin,org.vaadin,io.seventytwo.demo`

**Comment by tarekoraby** [comment]
Thanks for reporting. The generated projects now use '.' instead of '/'.
