### ISSUE TITLE
Starter project with multiple ImageList views fails to render in browser

### ISSUE THREAD

**Issue by krital** [vaadin/starters#40]
**Describe the bug**
As per the above title, Starter project with multiple ImageList views fails to render in browser using vaadin 22. The problem should be easy to fix, all views get the same custom element name in Java code & ts definition. 

**To Reproduce**
1. Create a starter project using vaadin 22 / Spring boot
2. Add more than one view containing Image List
3. Build with mvn
4. See error while rendering app in browser

**Expected behavior**
I expected the out of the box build to complete and run without errors. Renaming the custom elements resolves the issue

**Environment (please complete the following information):**
 - Spring boot starter
 - OS: OSX, Windows 10
 - Browser Chrome, safari
 - Vaadin version 22

**Comment by tarekoraby** [comment]
Thank you for the report! I could replicate the issue, and I think it's due to the generation of multiple `ImageCard` classes with the same tag.

**Comment by Artur-** [comment]
Now fixed, thanks
