### ISSUE TITLE
Checkbox label not displayed in Master Detail View

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#43]
The checkbox label is not set correctly

    <vaadin-checkbox id="important" style="padding-top: var(--lumo-space-m);">Important</vaadin-checkbox>

Should be 

     <vaadin-checkbox id="important" style="padding-top: var(--lumo-space-m);" label="Important"></vaadin-checkbox>

**Comment by Artur-** [comment]
Both ways should work equally well even though the first one is deprecated in V22+

There are two related issues that both will be fixed in the next Vaadin 23 alpha: 
- https://github.com/vaadin/web-components/issues/3323
- https://github.com/vaadin/flow-components/issues/2551

**Comment by tarekoraby** [comment]
The issues are now fixed, and the checkbox label property is now used in the starters.
