### ISSUE TITLE
@Autowired on constructor parameter may lead to problems

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#54]
Thanks for using constructor injection!

BUT @Autowired shouldn't be used on the parameters

    public AuthenticatedUser(@Autowired UserRepository userRepository) {
        this.userRepository = userRepository;
    }

The reason is: When someone adds a new parameter she may miss the annotation and the new parameter will not be injected.

Example

    public AuthenticatedUser(@Autowired UserRepository userRepository, RoleRepository roleRepository ) {
        this.userRepository = userRepository;
        this.roleRepository = roleRepository ;
    }

The roleRepository will be null!

When using constructors normally you want to have all parameter injected so use the annotation on the constructor level

    @Autowired
    public AuthenticatedUser( UserRepository userRepository) {
        this.userRepository = userRepository;
    }

When there is only one constructor the annotation can be omitted because there only one way to instantiate the class.

    public AuthenticatedUser(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

**Comment by tarekoraby** [comment]
Thanks for the suggestions @simasch!
