### ISSUE TITLE
Add spring boot plugin configuration for remote debug

### ISSUE THREAD

**Issue by mcollovati** [vaadin/starters#57]
After downloading an application from start.vaadin.com I usually need to set `jvmArguments` in spring-boot plugin configuration to be able to attach the IDE debugger.

Is it possible to have this configuration in pom file?
Even a commented entry will be fine.
This will save me the time I always spend to search for the configuration on the documentation :grin: 

```
<jvmArguments>
    -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
</jvmArguments>
```

**Comment by Artur-** [comment]
Any particular reason you are not launching the Application class from the IDE?

**Comment by mcollovati** [comment]
No particular reasons. I prefer to launch the application from a terminal outside the IDE

**Comment by Artur-** [comment]
I have nothing against adding it. I also use it occasionally. How do you launch the remote debugger from IntelliJ? Would it make sense to add something to the `.idea` folder also? For VS Code we could add a launch.json

**Comment by mcollovati** [comment]
I usually create a new "Remote JVM Debug" configuration. 
If the configuration is added uncommented it would be nice to have also the configuration ready in IntelliJ

![image](https://user-images.githubusercontent.com/4648894/175308880-f2a2e95d-f6a0-42f9-a92f-839446bad244.png)

**Comment by tarekoraby** [comment]
I'm not against making @mcollovati's life easier. But I worry about (a) bloating the pom file and (b) any possible unanticipated consequences that adding such settings would have on the functioning of the starters for people using the typical run-app-from-IDE approach.

**Comment by Artur-** [comment]
This does have the downside that if you try to start two apps at the same time, you get
```
[INFO] --- spring-boot-maven-plugin:2.7.1:run (default-cli) @ f ---
[INFO] Attaching agents: []
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
```

Maybe Start should randomize the port...
