### ISSUE TITLE
nav-item-icon unused

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#62]
There is a selector for class `.nav-item-icon` defined in the main-layout.css but not used anywhere.

**Comment by jouni** [comment]
True. That class name is only used as in indicator for the `<vcf-nav-item>` component that this element is an icon, so it applies some styles to it: https://github.com/vaadin/vcf-nav/blob/main/src/vcf-nav-item.ts#L160-L169

I’ll add a note about this behavior in the component readme.

**Comment by jouni** [comment]
Not a bug, working as intended, although perhaps something we want to reconsider in the official component.
