### ISSUE TITLE
AppNav does not highlight root context

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#66]
Since start.vaadin.com uses AppNav the RouteAlias is not highlighted.

AppNav does not use RouterLink which handles RouteAliases and set the attribute highlight accordingly.

AppNav only sets the attribute active if the URL matches the Route. 

Example:

    @Route(layout = AppMainLayout.class)
    @RouteAlias(value = "", layout = AppMainLayout.class)

http://localhost:8080
-> no active AppNavItem

http://localhost:8080/hello
-> AppNavItem is active

**Comment by simasch** [comment]
Additionally I think the AppNav should use RouterLink not simple Anchors.

**Comment by jouni** [comment]
> Additionally I think the AppNav should use RouterLink not simple Anchors.

Standard `<a>` links work automatically with the Flow and Hilla router. There’s no need for anything special in that regard in the component.

**Comment by MarcinVaadin** [comment]
Not relevant anymore after switching from AppNav to SideNav - root view is being highlighted.
