### ISSUE TITLE
Business App Starter bug: Sorting by Owner sorts icons instead of company names

### ISSUE THREAD

**Issue by javac9** [vaadin/starters#7]
**Describe the bug**
Business App Starter bug: Sorting by Owner sorts icons instead of company names
**To Reproduce**
1. Open "/accounts" page
2. Try to sort by "Owner"
3. Check if the company names are sorted
4. Sorting seems to be performed on icons instead

**Expected behavior**
Company names should be sorted

**Comment by javac9** [comment]
Actually, this is by design. The icons are assigned randomly on-the-fly. The icons appear "to get sorted" probably due to the fact they are simply being re-assigned randomly again.

I would however be glad (others as well I guess) if this is implemented properly in the future.

**Comment by anasmi** [comment]
Hi,

thank you for reporting the issue! 

I've created a pull request which should address the issue. (The randomness of the images was fixed already earlier, so the PR addresses the sorting order)

**Comment by anasmi** [comment]
The fix was merged a couple of days ago, so I will close the issue. Thank you again for reporting it! :)
