### ISSUE TITLE
Business App Starter bug: Incorrect icons is shown once user in on Account Details page

### ISSUE THREAD

**Issue by javac9** [vaadin/starters#8]
**Describe the bug**
Business App Starter bug: Incorrect icons is shown once user in on Account Details page

**To Reproduce**
1. Go to "/accounts" page
2. Click on any row/company
3. Note the main icon
4. The icons won't be the same as the one in the selected row on the previous page

**Comment by javac9** [comment]
Actually, this is by design. The icons are assigned randomly on-the-fly. I would however be glad (others as well I guess) if this is implemented properly in the future.

**Comment by anasmi** [comment]
Hi,

this was actually fixed a couple of days ago. Even if by design, it was misleading :) 

So thank you a lot for reporting the issue!
