### ISSUE TITLE
NPE on Grid Refresh in Master-Detail

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#80]
When restarting the app this line gives a NPE in certain situations:

    private void refreshGrid() {
        grid.select(null);
        grid.getLazyDataView().refreshAll();
    }

I don't understand why the LazyDataView is used and not the DataProvider.

Like this we have no issues:

    private void refreshGrid() {
        grid.select(null);
        grid.getDataProvider().refreshAll();
    }

**Comment by Artur-** [comment]
Nobody else understands why LazyDataView was used either

**Comment by jouni** [comment]
And to make it clear, these are the changes that were made:
<img width="884" alt="Screenshot 2022-10-05 at 15 16 32" src="https://user-images.githubusercontent.com/66382/194058235-4891bd30-c2b9-4d9c-8e91-77234aadfbf5.png">
