### ISSUE TITLE
Change ID generation strategy on entities

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#83]
The uuid-char ID generator is a Hibernate proprietary feature. Plus a UUID may not be the best strategy performance-wise.

    @Type(type = "uuid-char")
    private UUID id;

You should consider using only JPA standard features.

**Comment by Artur-** [comment]
Is there really any case when this is a performance problem? It could be an integer instead, with somewhat less security as you can guess the previous and next id

**Comment by Artur-** [comment]
JPA 3.1 seems to have ` @GeneratedValue(strategy = GenerationType.UUID)`

**Comment by simasch** [comment]
Sequence is the most common way. UUID generation is slow on mass inserts. Also depending on the database used UUIDs are stored differtly.
IMO we should use what the most common strategy is.

**Comment by simasch** [comment]
https://www.cybertec-postgresql.com/en/uuid-serial-or-identity-columns-for-postgresql-auto-generated-primary-keys/

**Comment by tarekoraby** [comment]
Isn't it the case that UUID is more favorable security-wise?

**Comment by simasch** [comment]
Not really because for performance improvement databases generate serial UUIDs

**Comment by Artur-** [comment]
Ids are now Long and use sequence based generation, which seems what most people recommend
