### ISSUE TITLE
Test output not visible

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#87]
You've added:

    
    <maven.test.redirectTestOutputToFile>true</maven.test.redirectTestOutputToFile>

This maybe a nice idea but redirects ALL test output to a file which is very inconvenient when building the application in a CI server like GitHub Actions.

Please remove this configuration.

If you just want to suppress the selenium output you should check how to configure logging! Btw it's not Selenium but netty and the driver manger.

**Comment by simasch** [comment]
One idea is to add a `logback-test.xml` to `src/test/resources` with this content :

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include resource="org/springframework/boot/logging/logback/defaults.xml"/>
	<include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

	<root level="DEBUG">
		<appender-ref ref="CONSOLE"/>
	</root>
	<logger name="io.github.bonigarcia" level="INFO"></logger>
	<logger name="io.netty" level="INFO"></logger>
	<logger name="org.asynchttpclient" level="INFO"></logger>
</configuration>
```

**Comment by Artur-** [comment]
What do you think @manolo ? It was added in https://github.com/vaadin/skeleton-starter-flow-spring/pull/869

**Comment by Artur-** [comment]
Using the given logback-test.xml seems to work nicely, thanks. Why is it needed though and how come setting the logging level for the same packages in application.properties has no effect?

**Comment by simasch** [comment]
That's a very good question! I'm not deep enough into Spring Boot logging.
