### ISSUE TITLE
deploy as war file

### ISSUE THREAD

**Issue by RienGenie** [vaadin/starters#88]
When you deploy the starter application as a war file the application will not be started in Tomcat or Jetty. 

When you let Application extends SpringBootServletInitializer this problem will be fixed.

**Comment by mstahv** [comment]
Hi @RienGenie!

This is kind of expected and described as a step in the Spring Boot docs as well. Was there some (outdated) instructions somewhere that suggest otherwise?

**Comment by Artur-** [comment]
Closing as this works as expected
