### ISSUE TITLE
Business App Starter bug: Tabs within DetailsDrawer on Payments page

### ISSUE THREAD

**Issue by javac9** [vaadin/starters#9]
**Describe the bug**
When you switch to the second or third tab within DetailsDrawer on the right on the Payments page, changing main grid selection will show the first tab contents but the tab selection will be of the previous selection.

**To Reproduce**
1. Go to Payments page
2. Select any row
3. Notice how the Details tab is selected by default (as the first one)
4. Switch to another tab, for example, next one: Attachements
5. Select another grid row
6. Notice how the Attachments tab is marked as selected/active also for this selection but the tab contents are that of Details tab (which should be selected)

**Comment by anasmi** [comment]
PR : https://github.com/vaadin/business-app-starter-flow/pull/162

**Comment by anasmi** [comment]
Created a pull request to address the issue. Unfortunately, as the repository is private, the pr is not visible, but the change relates to refactoring the `private DetailsDrawer createDetailsDrawer() ` method.

Thank you for reporting the issue!

**Comment by anasmi** [comment]
The fix was merged, so I will close the ticket. Thanks again! :)
