### ISSUE TITLE
PostgreSQL and LOB

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#94]
org.postgresql.util.PSQLException: LargeObjects (LOB) dürfen im Modus 'auto-commit' nicht verwendet werden

This is thrown because read methods in a JpaRepository are read-only and PostgreSQL requires a transaction to read the LOB.

As a workaround you have to set @Transacational on 
- AuthenticatedUser.get()
- UserDetailsServiceImpl.loadUserByUsername

**Comment by Artur-** [comment]
Deployed fix
