### ISSUE TITLE
Scope of driver dependency

### ISSUE THREAD

**Issue by simasch** [vaadin/starters#95]
<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

should be

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

Usually the developer doesn't want to directly interact with the database driver classes.

**Comment by Artur-** [comment]
This has been fixed and deployed
