### ISSUE TITLE
Project contains erroneous (static) launch config for VS Code

### ISSUE THREAD

**Issue by emarc** [vaadin/starters#98]
**Describe the bug**
The generated project contains a `.vscode/launch.json` which specifies the main class as `org.vaadin.example.Application` regardless of the package of the project (which is not even org.vaadin.example by default).

**To Reproduce**
1. Download any project
2. Open project in VS Code
3. Run or Debug (^F5 or F5)
4.`ConfigError: Main class 'org.vaadin.example.Application' doesn't exist in the workspace.`

**Expected behavior**
Project should run

![Markup 2022-12-09 at 09 18 36](https://user-images.githubusercontent.com/7479/206648005-d252aed5-933b-40a9-a0b2-b456380fd8fa.png)

**Comment by Artur-** [comment]
Fixed and deployed
